<form method="post" id="form">
    <table class="table table-bordered table-striped" id="checkAll">
        <thead>
        <tr>
            <td class="center" width="20" id="check"><input type="checkbox"/></td>
            <td class="center" width="35"></td>
            <td class="center" width="50"class="center">Doc</td>
            <td  class="center">Title</td>
            <td  class="center">Url</td>
            <td  class="center">Param</td>
            <td width="150"  class="center">Data</div></td>
            <td width="50"  class="center">Author</td>
            <td width="50"  class="center">Order</td>
            <td width="109"  class="center">Actions</td>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="13">
                <div class="pull-left">
                    <select  name="action" class="btn btn-inverse" style="width:130px;" id="action" onchange="this.form.submit($('form').attr('action', '<?=$this->url($route,array('lang'=>$lang));?>/' + $(this).val() + '/<?=$this->id?>'))">
                        <option value="">Select option</option>
                        <option value="duplicate">Duplicate</option>
                        <option value="delete">Delete</option>
                    </select>
                </div>
                <? $this->placeholder('urlPage')->set($this->url($route,array('lang'=>$lang,'id' => $id))); ?>
                <?=$this->paginationControl($this->qu_admin, 'Sliding', 'theme/pagination')?>
            </td>
        </tr>
        </tfoot>
        <tbody>
        <?php if (0 == count($this->qu_admin)){ ?>
            <?php }else{ ?>
            <?php foreach($this->qu_admin as $qu_admin){  ?>
            <tr id="item_<?=$qu_admin->id?>" char="<?=$qu_admin->order?>">
                <td class="center"><input type="checkbox" name="checkRow[]" value="<?=$qu_admin->id_lang?>" /></td>
                <td class="handle tableArrows center"><i class="icon-move"></i></td>
                <td class="center"><?=$this->QuDoc($qu_admin->type,$qu_admin->documents,'style="width:35px; height:35px;"')?></td>
                <td><?php echo $this->escapeHtml($qu_admin->title);?></td>
                <td class="center"><?php echo $this->escapeHtml($qu_admin->name);?></td>
                <td  class="center"><?php echo $this->escapeHtml($qu_admin->parameters);?></td>
                <td class="center"><?php echo $this->escapeHtml($qu_admin->modified);?></td>
                <td class="center"><?php echo $this->QuUser($qu_admin->id_author); ?></td>
                <td class="center"><?php echo $this->escapeHtml($qu_admin->order);?></td>
                <td style="vertical-align:middle;">
                    <div class="btn-group" style="float: left; margin:0 4px 0 0">
                        <button class="btn btn-small dropdown-toggle" data-toggle="dropdown"><span class="icon-cog" style="font-size:13px;"></span></button>
                        <ul class="dropdown-menu">
                            <?
                            foreach($this->QuLangNav() as $key=>$idima){
                                if(!$this->QuLangDetect($qu_admin->id_lang,$key)){
                                    echo '<a background-position:0 6px;" href="'.$this->url($route,array('action'=>'edit', 'id' => $qu_admin->id_lang,'lang'=>$key)).'">
                                <span class="icon-flag"></span> Traduir '.$idima.'</a>';
                                }
                            }
                            ?>
                            <li>
                                <a href="<?=$this->url($route,array('lang'=>$lang,'action'=>'duplicate','id'=>$id,'id_parent'=>$qu_admin->id));?>">
                                    <span class="icon-share-alt"></span>
                                    Duplicate
                                </a>
                            </li>
                            <li>
                                <a href="<?=$this->url($route,array('lang'=>$lang,'action'=>'delete','id'=>$id,'id_parent'=>$qu_admin->id));?>">
                                    <span class="icon-trash"></span>
                                   Delete
                                </a>
                            </li>
                        </ul>
                    </div>
                    <a href="<?=$this->url($route,array('lang'=>$lang,'action'=>'edit', 'id' => $qu_admin->id_lang));?>" class="btn btn-small" title="Edit"><span class="icon-pencil" style="font-size:13px;"></span></a>
                    <a href="<?=$this->url($route,array('lang'=>$lang,'action'=>'index','id' => $qu_admin->id_lang));?>" class="btn btn-small" title="Add"><span class="icon-plus" style="font-size:13px;"></span></a>
                </td>
            </tr>
                <? } ?>
            <? } ?>
        </tbody>
    </table>
</form>
<? if(isset($ajax)){ ?>
<script type="text/javascript">
    Sort();
</script>
<? } ?>
<script type="text/javascript">
    // Multi option
    $("#check input:checkbox").click(function() {
        var checkedStatus = this.checked;
        $("#checkAll tbody tr td:first-child input:checkbox").each(function() {
            this.checked = checkedStatus;
            if (checkedStatus == this.checked) {
                $(this).closest('.checker > span').removeClass('checked');
                $(this).closest('table tbody tr').removeClass('thisRow');
            }
            if (this.checked) {
                $(this).closest('.checker > span').addClass('checked');
                $(this).closest('table tbody tr').addClass('thisRow');
            }
        });
    });
    //Buscar
    function buscar(){
        var varnpp = '<?=$npp?>';
        var valor = $('#q').val().replace(' ','+');
        var valor = valor.replace(' ','+');
        var valor = valor.replace(' ','+');
        var valor = valor.replace(' ','+');
        $('.lopaLoad').css('display','block');
        $("#ajax").load('<?php echo $this->url($route,array('action'=>'ajax', 'id' => $id,'lang'=>$lang));?>?q=' + valor + '&npp=' + varnpp, function(){
            $('.lopaLoad').css('display','none');
        });
    }
    //Num Pages
    function NumPage(){
        var varq = '<?=$q?>';
        $('.headLoad').css('display','block');
        $("#ajax").load('<?php echo $this->url($route,array('action'=>'ajax', 'id' => $id,'lang'=>$lang));?>?npp=' + $("#npp").val() + '&q=' + varq, function(){
            $('.headLoad').css('display','none');
        });
    }
    $(".tPages a").click(function(){
        var varnpp = '<?=$npp?>';
        var varq = '<?=$q?>';
        var href = $(this).attr('href');
        $('.headLoad').css('display','block');
        $("#ajax").load(href.replace('<?=$route?>','<?=$route?>/ajax') + '&q=' + varq + '&npp=' + varnpp,function(){
            $('.headLoad').css('display','none');
        });
        return false;
    });
</script>



