<?
$form = $this->form;
$form->setAttribute('action',$this->url($route ,array('action' => $action,'id'=>$id,'lang'=>$lang)));
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();
?>
<?=$this->form()->openTag($form) . PHP_EOL;?>
<?=$this->formHidden($form->get('id'))?>
<?=$this->formHidden($form->get('id_parent')->setValue($id_parent))?>
<?=$this->formHidden($form->get('id_author')->setValue($id_author))?>
<?=$this->formHidden($form->get('modified')->setValue($modified))?>
<?=$this->formHidden($form->get('date')->setValue($modified))?>
<?=$this->formHidden($form->get('order'))?>
<?=$this->formHidden($form->get('id_lang')->setValue($id_lang))?>
<?=$this->formHidden($form->get('lang')->setValue($lang))?>

<div class="row-fluid">
    <div class="span12">
        Title
        <br />
        <?=$this->formInput($form->get('title'))?>
        <label generated="true" class="error"><?=$this->formElementErrors($form->get('title'))?></label>
    </div>
</div>
<hr>
<div class="row-fluid">
    <div class="span12">
        Parameter
        <br />
        <?=$this->formInput($form->get('name'))?>
        <label generated="true" class="error"><?=$this->formElementErrors($form->get('name'))?></label>
    </div>
</div>
<hr>
<div class="row-fluid">
    <div class="span12">
        Notes
        <br />
        <?=str_replace('<textarea','<textarea rows="5" ',$this->formTextarea($form->get('notes')))?>
        <label generated="true" class="error"><?=$this->formElementErrors($form->get('notes'))?></label>
    </div>
</div>
<hr>
<div class="row-fluid">
    <div class="span12">
        <input class="btn btn-info pull-right" value="Save" name="saveandclose" type="submit">
    </div>
</div>
<?=$this->form()->closeTag($form) . PHP_EOL;?>



