<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <?
    echo $this->headTitle('Qu ElFinder');
    echo $this->headLink()
        ->prependStylesheet($this->basePath($QuBasePath) . '/css/theme.css')
        ->prependStylesheet($this->basePath($QuBasePath) . '/css/elfinder.min.css')
        ->prependStylesheet($this->basePath($QuBasePath) . '/jquery/ui-themes/smoothness/jquery-ui-1.8.23.custom.css')
    ;
    echo $this->headScript()
        ->prependFile($this->basePath($QuBasePath) . '/js/back.js', 'text/javascript')
        ->prependFile($this->basePath($QuBasePath) . '/js/elFinder.options.js', 'text/javascript')
        ->prependFile($this->basePath($QuBasePath) . '/js/i18n/elfinder.ca.js', 'text/javascript')
        ->prependFile($this->basePath($QuBasePath) . '/js/elfinder.min.js', 'text/javascript')
        ->prependFile($this->basePath($QuBasePath) . '/jquery/jquery-ui-1.8.23.custom.min.js', 'text/javascript')
        ->prependFile($this->basePath($QuBasePath) . '/jquery/jquery-1.8.1.min.js', 'text/javascript')

    ;
    ?>
</head>
<body>

<div id="elfinder"></div>

<script type="text/javascript" charset="utf-8">

    // Helper function to get parameters from the query string.
    function getUrlParam(paramName) {
        var reParam = new RegExp('(?:[\?&]|&amp;)' + paramName + '=([^&]+)', 'i') ;
        var match = window.location.search.match(reParam) ;

        return (match && match.length > 1) ? match[1] : '' ;
    }

    $().ready(function() {
        var funcNum = getUrlParam('CKEditorFuncNum');

        var elf = $('#elfinder').elfinder({
            url : '<?=$ConnectorPath?>',
            lang : 'ca',
            height:'570',
            getFileCallback : function(file) {
                window.opener.CKEDITOR.tools.callFunction(funcNum, file.url);
                console.log(file.url);
                window.close();
            },
            resizable:false
        }).elfinder('instance');
    });

</script>
</body>
</html>