<?=$this->doctype()?>
<html lang="<?=$this->placeholder('lang')?>">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('QuAdminDemo')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?=$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <?=$this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath() . '/js/jquery-ui.min-1.8.js')
    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/js/jquery.min.js')
    ?>
    <?=$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/style.css')
    //->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
    ?>
</head>
<body>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="navbar navbar-inverse quadmin">
                <div class="navbar-inner">
                    <a class="brand" href="#">QuAdmin</a>
                    <?
                    $partial = array('theme/layout/menu.phtml', 'default');
                    $this->navigation('QuNavigation')->menu()->setPartial($partial);
                    echo $this->navigation()->menu()->render();
                    ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span2">
            <div class="row-fluid">
                <div class="well" style="padding-bottom:0;">
                    <div class="span6">
                        <?php if($this->zfcUserIdentity()){  echo $this->gravatar($this->zfcUserIdentity()->getEmail()); } ?>
                    </div>
                    <div class="span6">
                        <h5 style="line-height:0;"><?php echo $this->zfcUserDisplayName() ?></h5>
                        <ul class="nav">
                            <li><a href="http://gravatar.com" target="_blank" class="sProfile" >Gravatar</a></li>
                            <li><a href="<?=$this->url('zfcuser/profile')?>" class="sProfile" >Profile</a></li>
                            <li><a href="<?=$this->url('zfcuser/logout')?>" class="sLogout" >Logout</a></li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span12">
                    <?php  echo $this->navigation('QuNavigation')->menu()->renderSubMenu($this->navigation()->findOneByLabel('subNav'), 'nav nav-tabs nav-stacked');?>
                </div>
            </div>
        </div>
        <div class="span10">
            <?
                $breadcrumb = $this->navigation('QuNavigation')->breadcrumbs()->setLinkLast(false);
                if($breadcrumb != ''){
            ?>
            <div class="row-fluid">
                <div class="span12">
                    <ul class="breadcrumb">
                        <li>
                            <?=$breadcrumb->setSeparator('<span class="divider">/</span></li><li>'. PHP_EOL)?>
                        </li>
                        <?=$this->placeholder('Route')?>
                    </ul>
                </div>
            </div>
            <? } ?>
            <div class="row-fluid">
                <div class="span12">
                    <?=$this->content?>
                </div>
            </div>
        </div>
    </div>
</div>

<?=$this->inlineScript()?>
</body>
</html>