<?=$this->doctype()?>
<html lang="<?=$this->placeholder('lang')?>">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('QuAdminDemo')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?=$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <?=$this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ?>
    <?=$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/style.css')
    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
    ?>
</head>
<body>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3"><br>
            <div class="navbar navbar-inverse quadmin">
                <div class="navbar-inner">
                    <a class="brand" href="#">QuAdmin</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span3">
            <?=$this->content?>
        </div>
    </div>
</div>
</body>
</html>