<?
$form = $this->form;
$form->setAttribute('action',$this->url($route ,array('action' => $action,'id'=>$id,'lang'=>$lang)));
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();
?>
<?=$this->form()->openTag($form) . PHP_EOL;?>
<?=$this->formHidden($form->get('id'))?>
<?=$this->formHidden($form->get('id_parent')->setValue($id_parent))?>
<?=$this->formHidden($form->get('id_author')->setValue($id_author))?>
<?=$this->formHidden($form->get('modified')->setValue($modified))?>
<?=$this->formHidden($form->get('date')->setValue($modified))?>
<?=$this->formHidden($form->get('order'))?>
<?=$this->formHidden($form->get('id_lang')->setValue($id_lang))?>
<?=$this->formHidden($form->get('lang')->setValue($lang))?>
<div class="row-fluid">
    <div class="span9">
        <div class="row-fluid">
            <div class="span2">
                <?=$this->formLabel($form->get('title'))?>
            </div>
            <div class="span10">
                <?=$this->formInput($form->get('title'))?>
                <label generated="true" class="error"><?=$this->formElementErrors($form->get('title'))?></label>
            </div>
        </div>
        <hr>
        <div class="row-fluid">
            <div class="span2">
                <?=$this->formLabel($form->get('summary'))?>
            </div>
            <div class="span10">
                <?=str_replace('<textarea','<textarea rows="7" ',$this->formTextarea($form->get('summary')))?>
                <label generated="true" class="error"><?=$this->formElementErrors($form->get('summary'))?></label>
            </div>
        </div>
        <hr>
        <div class="row-fluid">
            <div class="span2">
                <?=$this->formLabel($form->get('documents'))?>
            </div>
            <div class="span10">
                <? $Doc = $this->QuDoc($form->get('type')->getValue(),$form->get('documents')->getValue(),'style="float:left; padding:0 10px;"');
                if($Doc){ echo $Doc; ?>
                    <br />
                    <a href="<?=$this->url($route,array('action'=>'deleteDoc','id'=>$id,'id_parent'=>$form->get('id')->getValue()))?>" class="btn btn-small">
                        <i class="icon-trash"></i>
                    </a>
                    <br />
                    <br />
                <? } ?>
                <input type="file" value="" name="documents" class="fileInput" id="fileInputS" />
                <?=$this->formHidden($form->get('documents'))?>
                <label generated="true" class="error"><?=$this->formElementErrors($form->get('documents'))?></label>
            </div>
        </div>
        <hr>
        <div class="row-fluid">
            <div class="span12">
                <?=str_replace('<textarea',' <textarea id="text" ',$this->formTextarea($form->get('content')))?>
                <?=$this->QuCkEditor(
                    'text',
                     array('Width' => "99%",
                          'Height' => "340",
                          'toolbar'=> array(
                              array('Source','Maximize'),
                              array('Templates','Styles','Format'),
                              array('Bold','Italic','Underline','Subscript','Superscript'),
                              array('NumberedList','BulletedList','Outdent','Indent'),
                              array('JustifyLeft','JustifyCenter','JustifyRight'),
                              array('Link','Unlink'),
                              array('Image','Table')
                              )
                          )
                     );
                ?>
                <label generated="true" class="error"><?=$this->formElementErrors($form->get('content'))?></label>
            </div>
        </div>
    </div>
    <div class="span3" >
        <div class="well" style="background:#fff">
        <div class="row-fluid">
            <div class="span12">
                <input class="btn btn-primary"   style="width:100%; margin-bottom:10px!important;"   value="Save"           name="save"         type="submit">
                <input class="btn btn-info"      style="width:100%; margin-bottom:10px!important;"   value="Save & Close"   name="saveandclose" type="submit">
                <input class="btn btn-success"   style="width:100%;"                                 value="Close"          name="close"        type="submit">
            </div>
        </div>
        <hr>
        <div class="row-fluid">
            <div class="span3"><?=$this->formLabel($form->get('name'))?></div>
            <div class="span9">
                <?=$this->formInput($form->get('name'))?>
                <label generated="true" class="error"><?=$this->formElementErrors($form->get('name'))?></label>
            </div>
        </div>
        <hr>
        <div class="row-fluid">
            <div class="span3"><?=$this->formLabel($form->get('status'))?></div>
            <div class="span9">
                <?=str_replace('<select','<select  data-placeholder="Select"  class="span10" ',$this->formSelect($form->get('status')))?>
                <label generated="true" class="error"><?=$this->formElementErrors($form->get('status'))?></label>
            </div>
        </div>
        <hr>
        <div class="row-fluid">
            <div class="span3">Params</div>
            <div class="span9">
                <?=str_replace('<select','<select  data-placeholder="Select"  class="span10" ',$this->formSelect($form->get('parameters')))?>
                <label generated="true" class="error"><?=$this->formElementErrors($form->get('parameters'))?></label>
            </div>
        </div>
    </div>
</div>
</div>
<?=$this->form()->closeTag($form) . PHP_EOL;?>