<?=
    $this->render('theme/editor1/route.phtml').
    $this->render('theme/editor1/lang.phtml').
    $this->QuFlashMessages().
    $this->render('theme/editor1/title.phtml');
?>

    <a href="<?php echo $this->url($route, array('action'=>'add','id'=>$id,'lang'=>$lang));?>" title="Crear" class="btn">
        <span class="icon-plus"></span> Add
    </a>
    <div class="navbar-form pull-right">
        <input type="text" placeholder="Search" id="q" name="q" onKeyUp="return buscar()">
        <select id="npp"  class="btn input-mini btn-inverse">
            <option value="10" selected="selected">10</option>
            <option value="25">25</option>
            <option value="50">50</option>
            <option value="100">100</option>
        </select>
    </div>
    <div class="clearfix"><br></div>
    <div id="ajax">
        <?=$this->render('theme/editor1/ajax.phtml')?>
    </div>
    <script type="text/javascript">
        $("#npp").change(function () {
            NumPage();
        });
        Sort();
        function Sort(){
            var norder = '&n=' + $('#checkAll tbody tr').attr('char') + '&page=<?=$page?>';
            var fixHelperModified = function(e, tr) {
                var $originals = tr.children();
                var $helper = tr.clone();
                $helper.children().each(function(index)
                {
                    $(this).width($originals.eq(index).width())
                });
                return $helper;
            };
            $("tbody").sortable({
                helper:fixHelperModified,
                opacity: 0.6,
                handle: ".handle",

                start: function(e, ui){
                    ui.placeholder.height(ui.item.height()+1);
                },
                update:function (e) {
                    var order = $('#checkAll tbody').sortable('serialize');
                    $('.headLoad').css('display','block');
                    $("#ajax").load('<?php echo $this->url($route,array('action'=>'ajax', 'id' => $id,'lang'=>$lang));?>' + "?" + order + norder, function(){
                        $('.headLoad').css('display','none');
                    });
                }
            }).disableSelection();
        }
    </script>