<?
    $menu = '';
    foreach($this->QuRout($id,$lang) as $key => $Rut){
        $menu .= '
    <li '.$this->QuActive($Rut['id_lang'],$id_parent,'class="current"').'>
        <a href="'.$this->url($route,array('id'=>$Rut['id_lang'],'id_parent'=>$Rut['id_parent'],'lang'=>$lang)).'">
            '.$Rut['title'].'
        </a>
        <span class="divider">/</span>
    </li>';
    }
    $this->placeholder('Route')->set($menu);