<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'PHPMailer'              => __DIR__ . '/src/PHPMailer/class.phpmailer.php',
    'phpmailerException'     => __DIR__ . '/src/PHPMailer/class.phpmailer.php',
    'POP3'                   => __DIR__ . '/src/PHPMailer/class.pop3.php',
    'SMTP'                   => __DIR__ . '/src/PHPMailer/class.smtp.php',
    'ntlm_sasl_client_class' => __DIR__ . '/src/PHPMailer/extras/ntlm_sasl_client.php',
    'phpmailerTest'          => __DIR__ . '/src/PHPMailer/test/phpmailerTest.php',
    'phpmailerAppException'  => __DIR__ . '/src/PHPMailer/test_script/index.php',
);