<?php

    // Load Page
    $this->placeholder('lang')->set($lang);

    $content         = $this->cont(false,'row','url',false);
    $content_in_home = $this->cont(false,'all',false,$content['id']);

    $this->headTitle()->prepend($content['title']);
    $this->placeholder('url')->set($content['name']);

    if($content['name'] == 'home'){

        // Content Loop Home
        foreach($content_in_home as $content_home){
            echo  $this->partial('qu-web-demo/content/page-options.phtml',array('content'=>$content_home));
        }

    }else{

        $form = $this->render('qu-web-demo/content/form.phtml');

        // Head main menu
        echo $this->partial('qu-web-demo/content/head.phtml',array('content'=>$content));

        // Sub menu and Pages
        echo str_replace('{from-contact}',$form,$this->partial('qu-web-demo/content/page.phtml',array('sub_content'=>$content)));




    }