<?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    $span = 'span12';
?>

<? if($this->send == 'error'){ ?>
<div class="row-fluid contact">
    <div class="span12 error">

        <div class="alert">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>Warning!</strong> <?=$this->translate('error')?>
        </div>

    </div>
</div>
<? } ?>


<div class="row-fluid contact">
    <? if($this->send != 'error' and $this->send != ''){ ?>
    <?=$this->send?>
    <? }else{ ?>
    <div class="span6">

        <label><?=$this->translate('Nombre y apellidos')?></label>
        <?=str_replace('<input','<input class="'.$span.'" ',$this->formInput($form->get('nom')))?>
        <?=$this->formElementErrors($form->get('nom'))?>

        <label><?=$this->translate('E-mail')?></label>
        <?=str_replace('<input','<input class="'.$span.'" ',$this->formInput($form->get('from')))?>
        <?=$this->formElementErrors($form->get('from'))?>

        <label><?=$this->translate('Asunto')?></label>
        <?=str_replace('<input','<input class="'.$span.'" ',$this->formInput($form->get('subject')))?>
        <?=$this->formElementErrors($form->get('subject'))?>

    </div>
    <div class="span6">

        <label><?=$this->translate('Mensaje')?></label>
        <?=str_replace('<textarea','<textarea rows="5" class="'.$span.'" ',$this->formTextarea($form->get('body')))?>
        <?=$this->formElementErrors($form->get('body'))?>

        <?=str_replace('<input','<input class="btn btn-primary '.$span.'" ',str_replace('Enviar',$this->translate('Enviar'),$this->formInput($form->get('Send'))))?>
        <?=$this->formElementErrors($form->get('Send'))?>

    </div>
    <? } ?>
</div>
<?php echo $this->form()->closeTag() ?>
