<?php
    // Header
    if(strlen($content['title']) > 1)
    {
        echo '<div class="hero-unit">';
                echo '<h1>'.$content['title'].'</h1>';
                echo '<p>'.$content['summary'].'</p>';
                $img = $this->img($content['documents'],$content['type'],false);
                echo '<div class="description">'.$content['content'].'</div>';
        echo '</div>';

        if($img)
        {
            echo '<div class="image">'.$img.'</div>';
        }
    }