
<div class="row-fluid grid" style="margin-top:20px;">

    <?php

    $grid_fluid = round(12/$grid);
    $count = -1;  foreach($content as $c){ $count++;

    if($count == $grid){ $count = 0;  echo '</div><div class="row-fluid grid">'; }

    ?>
        <div class="span<?=$grid_fluid?>">

            <p><?=$this->img($c['documents'],$c['type'],false)?></p>

            <h5><?=$c['title']?></h5>

            <p><?=$c['summary']?></p>

            <?=$c['content']?>

        </div>

    <?php } ?>

</div>
