

<div class="accordion" id="accordion2">

    <?php $cont = 0; foreach($content as $c){ $cont++; ?>

        <div class="accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#<?=$c['name']?>">
                    <?=$c['title']?>
                </a>
            </div>
            <div id="<?=$c['name']?>" class="accordion-body collapse<?php if($cont == 1){ echo ' in'; } ?>">
                <div class="accordion-inner">
                    <h4><?=$c['summary']?></h4>
                    <p><?=$this->img($c['documents'],$c['type'],false)?></p>
                    <?=$c['content']?>
                </div>
            </div>
        </div>

    <?php } ?>

</div>
