<?php

    foreach($content as $c)
    {
        // Header
        if($c['title'])
        {
            echo '<h2>'.$c['title'].'</h2>';
        }

        if($c['summary'])
        {
            echo '<p class="summary">'.$c['summary'].'</p>';
        }

        $img = $this->img($c['documents'],$c['type'],false);
        if($img)
        {
            echo '<p class="image">'.$img.'</p>';
        }

        // Content
        if($c['content'])
        {
            echo '<div class="row-fluid">'.$c['content'].'</div>';
        }
    }
