

<ul id="myTab" class="nav nav-tabs">

    <?php $count = 0; foreach($content as $c){ $count++;  ?>

        <li class="<?php if($count == 1){ echo 'active'; }?>">
            <a href="#<?=$c['name']?>"  data-toggle="tab">
                <?=$c['title']?>
            </a>
        </li>

    <?php } ?>

</ul>
<div id="myTabContent" class="tab-content">

    <?php $count2 = 0; foreach($content as $c){ $count2++;  ?>

        <div class="tab-pane fade<?php if($count2 == 1){ echo ' active in'; }?>"  id="<?=$c['name']?>">
             <h5><?=$c['summary']?></h5>
             <p><?=$this->img($c['documents'],$c['type'],false)?></p>
             <?=$c['content']?>
        </div>

    <?php } ?>

</div>


