
    <div class="row-fluid">
        <div class="span3 bs-docs-sidebar">
            <ul class="nav nav-tabs nav-stacked">
                <?php
                     // Sub nav
                     echo $this->partial('qu-web-demo/content/nav-sub.phtml',array(

                            'menu'      =>  $this->cont(false,'all',false,$sub_content['id_lang']),
                            'parent'    =>  $sub_content['name']

                    ));
                ?>
            </ul>
        </div>
        <div class="span9">
            <?php

                $content = $this->cont(false,'row','url2',$sub_content['id_lang']);
                $this->headTitle()->prepend($content['title']);
                $this->placeholder('url2')->set($content['name']);

                if($content['id_parent'] != ''){

                    // Head & Content Sub menu
                    echo $this->partial('qu-web-demo/content/page-content.phtml',array('content'=>$content));

                    // Page loops sub menu
                    echo  $this->partial('qu-web-demo/content/page-options.phtml',array('content' => $content));
                }
            ?>
        </div>
    </div>