<?php

    if(strlen($content['title']) > 1)
    {

        echo '<div class="content-sub">';

            echo '<h2>'.$content['title'].'</h2>';


            if(strlen($content['title']) > 1)
            {
                echo '<p>'.$content['summary'].'<p>';
            }

            $img = $this->img($content['documents'],$content['type'],false);

            if($img){

                echo   '<p class="image">'.$img.'</p>';

            }

            if(strlen($content['title']) > 1)
            {
                echo $content['content'];
            }

        echo '</div>';

    }
?>