<?php
$baseUrl = $this->placeholder('urlPage');
if($this->pageCount){
?>
<div class="pagination pull-right tPages">
    <ul>
        <? if(isset($this->previous)){?>
            <li><a href="<?=$baseUrl; ?>?page=<?=$this->first; ?>">«</a></li>
            <li><a href="<?=$baseUrl; ?>?page=<?=$this->previous; ?>">««</a></li>
        <? } ?>
        <? foreach($this->pagesInRange as $page){ ?>
            <li<? if($page == $this->current){ echo ' class="active"'; } ?>>
                <a href="<?=$baseUrl; ?>?page=<?=$page; ?>"><?=$page; ?></a>
            </li>
        <? } ?>
        <? if(isset($this->next)){ ?>
            <li><a href="<?=$baseUrl; ?>?page=<?=$this->next; ?>">»»</a></li>
            <li><a href="<?=$baseUrl; ?>?page=<?=$this->last; ?>">»</a></li>
        <? } ?>
    </ul>
</div>
<div class="pull-right pg">
    <label>Showing <?=$this->firstItemNumber?> to <?=$this->lastItemNumber?> of  <?=$this->totalItemCount?> records</label>
</div>
<? }