<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('QuModules'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>



    <a href="https://github.com/Celtico?tab=repositories"><img style="position: absolute; top: 0; right: 0; border: 0; z-index:9999;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>


    <div class="navbar navbar-static-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar " data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>">
                        QuModules
                    </a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <?php $uri = $_SERVER['REQUEST_URI']; ?>
                            <li <?php if( $uri == '/quplupload'){ echo  'class="active"'; } ?>><a href="<?php echo $this->url('quplupload') ?>">Plupload</a></li>
                            <li <?php if( $uri == '/quelfinder'){ echo  'class="active"'; } ?>><a href="<?php echo $this->url('QuElFinder') ?>">ElFinder</a></li>
                            <li <?php if( $uri == '/quckeditor'){ echo  'class="active"'; } ?>><a href="<?php echo $this->url('QuCKEditor') ?>">CKEditor</a></li>
                            <li <?php if( $uri == '/quadmin'){ echo  'class="active"'; } ?>><a href="<?php echo $this->url('quadmin') ?>">QuAdmin</a></li>
                            <li><a href="">PHPMailer</a></li>
                            <li><a href="">TcPdf</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <?php if($uri != '/'){ ?>





            <div class="home-temp-in">
                <div class="container">
                    <div class="row">
                        <div class="span12">
                        <blockquote>modules for <a href="http://framework.zend.com/">Zend Framework 2</a> </blockquote>
                            </div>
                    </div>
                </div>
            </div>



        <?php } ?>



            <?php echo $this->content; ?>

        <div class="container">
            <hr>
            <footer>


                    <div class="row">
                        <div class="span3">
                            <p>
                                Soportet by <a href="http://cenics.cat/">Cel Tico Petit</a><br>
                                For any question:&nbsp;<a href="mailto:cel@cenics.net">cel@cenics.net</a>
                            </p>
                            <p>
                                Other project<br>
                                <a href="http://dibuixa.com/">Dibuixa</a>
                                Version 0.0.1-beta
                            </p>

                        </div>
                        <div class="span3">
                            <p>
                                Organization<br>
                                <a href="http://cenics.cat/">Cenics scp</a><br>

                                Social networks<br>
                                <a href="http://www.facebook.com/10cenics">facebook</a>
                                |  <a href="https://twitter.com/cenics">twitter</a>
                            </p>
                        </div>
                        <div class="span3">

                        </div>
                        <div class="span3">
                            <p>
                                <a rel="license" href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons Attribution 3.0 License"><img src="//i.creativecommons.org/l/by/3.0/88x31.png" alt="License"></a>
                            </p>
                            <div style="display: inline;" xmlns:cc="http://creativecommons.org/ns#" about="http://creativecommons.org">
                                <p>

                                        Except where otherwise
                                        <a class="subfoot" href="http://creativecommons.org/policies#license">noted</a>,
                                        content on
                                        <span href="http://creativecommons.org" property="cc:attributionName" rel="cc:attributionURL">this site</span>
                                        is licensed under a
                                        <a rel="license" href="http://creativecommons.org/licenses/by/3.0/" class="subfoot">
                                            Creative Commons Attribution 3.0 License</a>.

                                </p>
                            </div>
                        </div>
                </div>

            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>


    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-39549337-1', 'qumodules.com');
        ga('send', 'pageview');

    </script>

    
    </body>
</html>
