

<div class="home-temp">
    <div class="container">
    <div class="row">

        <div class="span12">
            <h1>QuModules</h1>
            modules for Zend Framework 2
            </div>

    </div>
        </div>
</div>
<div class="container">
<div class="row">


    <div class="span4">
        <h2 class="well">
            <a href="/quplupload">
                Plupload

            </a>
        </h2>
    </div>
   <div class="span4">
       <h2 class="well">
          <a href="/quelfinder">
              ElFinder

           </a>
       </h2>
   </div>
    <div class="span4">
        <h2 class="well">
            <a href="/quckeditor">
                CKEditor

            </a>
        </h2>
    </div>


</div>

<div class="row">

    <div class="span4">
        <h2 class="well">
            <a href="/quadmin">
                QuAdmin

            </a>
        </h2></div>

    <div class="span4">
        <h2 class="well">
            <a href="#">
                PhpMailer

            </a>
        </h2></div>

    <div class="span4">
        <h2 class="well">
           <a href="#">
                TcPdf

            </a>
        </h2>
    </div>

</div>

<div class="row">
    <div class="span12">
        <br><br>
        <div id="disqus_thread"></div>
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'qumodules'; // required: replace example with your forum shortname

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    </div>
</div>
</div>